import { Locale } from '@lib/i18n';
import type { Metadata } from 'next';
import { getTranslations, getLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: process.env.ROBOTS,
};

// export async function generateStaticParams() {
//   const posts = await fetch('https://.../posts').then((res) => res.json())

//   return posts.map((post) => ({
//     slug: post.slug,
//   }))
// }

export default async function Home({
  params,
}: {
  params: { slug?: string[] };
}) {
  const locale = (await getLocale()) as Locale;
  const t = await getTranslations('Home');

  return (
    <main>
      {t('hello')} - {locale} - {params.slug?.join(', ')}
    </main>
  );
}
