import type { Metadata } from 'next';
import Image from 'next/image';
import { PortableTextBlock } from 'next-sanity';
import { Locale } from '@lib/i18n';
import { getTranslations, getLocale } from 'next-intl/server';
import SanityContent from '@components/SanityContent';
import { getPageSlugs, getSinglePage } from '@lib/sanity/fetchers';
import { Slug } from 'types/sanity.types';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: process.env.ROBOTS,
};

export async function generateStaticParams() {
  const allSlugs = await getPageSlugs();

  const res = allSlugs.flatMap((slugItem, i) => {
    const fieldArray = Object.entries(slugItem.slug);

    const localizedSlugs = fieldArray.filter((item) => item[0] !== '_type');

    return localizedSlugs.map((field) => {
      if (field[0] !== '_type') {
        const slug =
          (field[1] as Slug).current === '/' ? '' : (field[1] as Slug).current;

        return `/${field[0]}/${slug}`;
      }
    });
  });

  return res;
}

export default async function Home({
  params,
}: {
  params: { slug?: string[] };
}) {
  const t = await getTranslations('Home');
  const locale = (await getLocale()) as Locale;
  const slug = params?.slug ?? ['/'];

  const pageData = await getSinglePage(locale, slug[0]);

  console.log('pageData', pageData);

  return (
    <main>
      Generic {t('hello')}: {locale} | {params.slug}
      {pageData.body && (
        <>
          <Image
            src={pageData.pageImage.url}
            width={500}
            height={300}
            alt={'fff'}
            style={{ width: '60%' }}
          />
          <SanityContent
            className="mx-auto max-w-2xl"
            value={pageData.body[locale] as PortableTextBlock[]}
          />
        </>
      )}
    </main>
  );
}
