import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import ContentWrapper from './components/ContentWrapper';

const baseFont = Ubuntu({
  subsets: ['latin'],
  weight: '300'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: process.env.ROBOTS
};

console.log('NODE_ENV', process.env.NODE_ENV);

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body className={baseFont.className}>
        <div className="container h-lvh mx-auto bg-white">
          <Header />
          <ContentWrapper>{children}</ContentWrapper>
        </div>
      </body>
    </html>
  );
}
