export const metadata = {
  title: 'Aviva Zala Studio',
  description: 'Generated by Chris',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
